"""
AdTicks — White-label SEO Report generator.

Builds a multi-section PDF or Markdown report bundling:
    - Executive summary
    - Site audit highlights (errors, warnings, score)
    - Top keyword opportunities
    - Backlink profile snapshot
    - Core Web Vitals summary
    - Local SEO consistency snapshot

Uses reportlab when available, otherwise emits Markdown that can be served
back to the frontend or converted client-side.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    )
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def build_markdown_report(
    project_name: str,
    summary: dict[str, Any],
    branding: dict[str, Any] | None = None,
) -> str:
    """Markdown fallback report — always available."""
    branding = branding or {}
    brand_name = branding.get("brand_name", "AdTicks")
    primary = branding.get("primary_color", "#6366F1")
    today = datetime.now(tz=timezone.utc).strftime("%B %d, %Y")

    lines: list[str] = [
        f"# {brand_name} — SEO Performance Report",
        f"## {project_name}",
        f"_{today}_",
        "",
        "## Executive Summary",
        "",
        f"- Site Health Score: **{summary.get('site_score', 'N/A')}/100**",
        f"- Pages Crawled: **{summary.get('pages_crawled', 0)}**",
        f"- Total Issues: **{summary.get('total_issues', 0)}** "
        f"({summary.get('errors', 0)} errors / {summary.get('warnings', 0)} warnings)",
        f"- Backlinks: **{summary.get('backlinks', 0)}** from {summary.get('referring_domains', 0)} domains",
        f"- Keywords tracked: **{summary.get('keywords_tracked', 0)}** "
        f"({summary.get('top10_keywords', 0)} in top 10)",
        f"- Average Core Web Vitals score: **{summary.get('cwv_score', 'N/A')}**",
        "",
        "## Top Issues to Fix",
        "",
    ]
    for issue in (summary.get("top_issues") or [])[:10]:
        lines.append(f"- **[{issue.get('severity', 'warning').upper()}]** "
                     f"{issue.get('message')} — _{issue.get('url')}_")

    lines.extend([
        "",
        "## Top Keyword Opportunities",
        "",
        "| Keyword | Volume | Difficulty | Position |",
        "|---|---|---|---|",
    ])
    for kw in (summary.get("top_keywords") or [])[:10]:
        lines.append(
            f"| {kw.get('keyword')} | {kw.get('volume', 0)} | "
            f"{kw.get('difficulty', 0)} | {kw.get('position', 'N/A')} |"
        )

    lines.extend([
        "",
        "## Backlink Profile",
        "",
        f"- Referring Domains: **{summary.get('referring_domains', 0)}**",
        f"- New Links (30d): **{summary.get('new_links_30d', 0)}**",
        f"- Lost Links (30d): **{summary.get('lost_links_30d', 0)}**",
        f"- Toxic Domains: **{summary.get('toxic_domains', 0)}**",
        "",
        f"---",
        f"_Generated by {brand_name}. Brand color: `{primary}`._",
    ])
    return "\n".join(lines)


def build_pdf_report(
    project_name: str,
    summary: dict[str, Any],
    output_path: str,
    branding: dict[str, Any] | None = None,
) -> str:
    """Generate a PDF report. Falls back to markdown text file if reportlab missing."""
    branding = branding or {}
    if not REPORTLAB_AVAILABLE:
        md = build_markdown_report(project_name, summary, branding)
        md_path = output_path.replace(".pdf", ".md")
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md)
        return md_path

    primary = HexColor(branding.get("primary_color", "#6366F1"))
    brand_name = branding.get("brand_name", "AdTicks")

    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=0.7 * inch, rightMargin=0.7 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"], textColor=primary, fontSize=24, spaceAfter=14
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"], textColor=primary, fontSize=16, spaceBefore=18, spaceAfter=8
    )
    body = styles["BodyText"]
    body.fontSize = 10
    body.leading = 14

    today = datetime.now(tz=timezone.utc).strftime("%B %d, %Y")
    flow = [
        Paragraph(f"{brand_name} — SEO Performance Report", title_style),
        Paragraph(f"<b>Project:</b> {project_name}", body),
        Paragraph(f"<b>Generated:</b> {today}", body),
        Spacer(1, 0.3 * inch),
        Paragraph("Executive Summary", h2_style),
    ]

    summary_table_data = [
        ["Metric", "Value"],
        ["Site Health Score", f"{summary.get('site_score', 'N/A')} / 100"],
        ["Pages Crawled", str(summary.get("pages_crawled", 0))],
        ["Total Issues", str(summary.get("total_issues", 0))],
        ["Errors", str(summary.get("errors", 0))],
        ["Warnings", str(summary.get("warnings", 0))],
        ["Backlinks", str(summary.get("backlinks", 0))],
        ["Referring Domains", str(summary.get("referring_domains", 0))],
        ["Keywords Tracked", str(summary.get("keywords_tracked", 0))],
        ["Top 10 Keywords", str(summary.get("top10_keywords", 0))],
    ]
    table = Table(summary_table_data, colWidths=[3 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), primary),
        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F9FAFB"), HexColor("#FFFFFF")]),
        ("GRID", (0, 0), (-1, -1), 0.25, HexColor("#E5E7EB")),
    ]))
    flow.append(table)

    flow.append(Paragraph("Top Issues", h2_style))
    issues = summary.get("top_issues") or []
    for issue in issues[:10]:
        sev = issue.get("severity", "warning").upper()
        flow.append(Paragraph(
            f"<b>[{sev}]</b> {issue.get('message')} <font color='#6B7280'><br/>{issue.get('url')}</font>",
            body,
        ))
        flow.append(Spacer(1, 0.06 * inch))

    flow.append(Paragraph("Top Keyword Opportunities", h2_style))
    kws = summary.get("top_keywords") or []
    if kws:
        kw_data = [["Keyword", "Volume", "Difficulty", "Position"]] + [
            [k.get("keyword", ""), str(k.get("volume", 0)), str(k.get("difficulty", 0)), str(k.get("position", "—"))]
            for k in kws[:10]
        ]
        kw_table = Table(kw_data, colWidths=[3 * inch, 1 * inch, 1 * inch, 1 * inch])
        kw_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), primary),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F9FAFB"), HexColor("#FFFFFF")]),
            ("GRID", (0, 0), (-1, -1), 0.25, HexColor("#E5E7EB")),
        ]))
        flow.append(kw_table)

    doc.build(flow)
    return output_path
