"""add_ai_scans_enabled_to_project

Revision ID: 07c0c267c611
Revises: add_gsc_integration
Create Date: 2026-04-25 12:42:30.601582
"""
from alembic import op
import sqlalchemy as sa


revision = '07c0c267c611'
down_revision = 'add_gsc_integration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ai_scans_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ai_scans_enabled')
    # ### end Alembic commands ###
