"""add response_text to responses table

Revision ID: 215342b3abec
Revises: add_plan_to_user_v1
Create Date: 2026-04-24 09:55:15.818919
"""
from alembic import op
import sqlalchemy as sa


revision = '215342b3abec'
down_revision = 'add_plan_to_user_v1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('response_text', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'response_text')
    # ### end Alembic commands ###
