"""add_remote_log_fields_to_project

Revision ID: 7bc1c7cc1960
Revises: seo_extra_v1
Create Date: 2026-05-02 20:31:52.849754
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7bc1c7cc1960'
down_revision = 'seo_extra_v1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Create index with if_not_exists (PostgreSQL specific)
    try:
        # Use raw SQL with IF NOT EXISTS for PostgreSQL
        conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_keywords_cluster_id ON keywords (cluster_id)"))
    except:
        pass
    
    # Alter keywords.search_volume_history if not already altered
    try:
        op.alter_column('keywords', 'search_volume_history',
                   existing_type=postgresql.JSONB(astext_type=sa.Text()),
                   type_=sa.JSON(),
                   existing_nullable=True)
    except:
        # Column might already be JSON type, that's fine
        pass
    
    # Add columns to projects if they don't exist
    columns = [c['name'] for c in inspector.get_columns('projects')]
    if 'remote_log_url' not in columns:
        op.add_column('projects', sa.Column('remote_log_url', sa.String(length=1024), nullable=True))
    if 'log_sync_enabled' not in columns:
        op.add_column('projects', sa.Column('log_sync_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Drop columns if they exist
    columns = [c['name'] for c in inspector.get_columns('projects')]
    if 'log_sync_enabled' in columns:
        op.drop_column('projects', 'log_sync_enabled')
    if 'remote_log_url' in columns:
        op.drop_column('projects', 'remote_log_url')
    
    # Drop index with IF EXISTS
    try:
        conn.execute(sa.text("DROP INDEX IF EXISTS ix_keywords_cluster_id"))
    except:
        pass
    
    # Alter column back
    try:
        op.alter_column('keywords', 'search_volume_history',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
    except:
        pass
    # ### end Alembic commands ###
