"""add_remote_log_fields_to_project

Revision ID: 7bc1c7cc1960
Revises: seo_extra_v1
Create Date: 2026-05-02 20:31:52.849754
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7bc1c7cc1960'
down_revision = 'seo_extra_v1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: status, first_seen, and last_seen columns for backlinks are already added in fix_seo_suite_schema_v1
    op.alter_column('keywords', 'search_volume_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_keywords_cluster_id'), 'keywords', ['cluster_id'], unique=False)
    op.add_column('projects', sa.Column('remote_log_url', sa.String(length=1024), nullable=True))
    op.add_column('projects', sa.Column('log_sync_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'log_sync_enabled')
    op.drop_column('projects', 'remote_log_url')
    op.drop_index(op.f('ix_keywords_cluster_id'), table_name='keywords')
    op.alter_column('keywords', 'search_volume_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
